/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:42d912dd-e6a3-4de1-a808-525cc6d544e1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Uvk0XvRNr",
    "aws_user_pools_web_client_id": "28ae560eli4pe7669sft3fthus",
    "oauth": {}
};


export default awsmobile;
