/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:42d912dd-e6a3-4de1-a808-525cc6d544e1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Uvk0XvRNr",
    "aws_user_pools_web_client_id": "28ae560eli4pe7669sft3fthus",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://yjb5iwk3irca7ncz2lq66afuxy.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ztss2ayn4zabrgs2elc4addje4"
};


export default awsmobile;
